insert into "MDATA"."MDG_PARTY_STATUS" ("LOCALITY","STATUSCODE", "DESCRIPTION", "CREATED_AT", "CREATED_BY", "UPDATED_AT", "UPDATED_BY") values('Global', '10' ,'Active', current timestamp, 'sql import' , NULL, NULL);
insert into "MDATA"."MDG_PARTY_STATUS" ("LOCALITY","STATUSCODE", "DESCRIPTION", "CREATED_AT", "CREATED_BY", "UPDATED_AT", "UPDATED_BY") values('Global', '30' ,'Global Inactivated', current timestamp, 'sql import' , NULL, NULL);
insert into "MDATA"."MDG_PARTY_STATUS" ("LOCALITY","STATUSCODE", "DESCRIPTION", "CREATED_AT", "CREATED_BY", "UPDATED_AT", "UPDATED_BY") values('Global', '31' ,'Embargo', current timestamp, 'sql import' , NULL, NULL);
insert into "MDATA"."MDG_PARTY_STATUS" ("LOCALITY","STATUSCODE", "DESCRIPTION", "CREATED_AT", "CREATED_BY", "UPDATED_AT", "UPDATED_BY") values('Global', '32' ,'Group Loss', current timestamp, 'sql import' , NULL, NULL);
insert into "MDATA"."MDG_PARTY_STATUS" ("LOCALITY","STATUSCODE", "DESCRIPTION", "CREATED_AT", "CREATED_BY", "UPDATED_AT", "UPDATED_BY") values('Global', '33' ,'Duplicatev', current timestamp, 'sql import' , NULL, NULL);
insert into "MDATA"."MDG_PARTY_STATUS" ("LOCALITY","STATUSCODE", "DESCRIPTION", "CREATED_AT", "CREATED_BY", "UPDATED_AT", "UPDATED_BY") values('Global', '34' ,'Commercial Decision', current timestamp, 'sql import' , NULL, NULL);
insert into "MDATA"."MDG_PARTY_STATUS" ("LOCALITY","STATUSCODE", "DESCRIPTION", "CREATED_AT", "CREATED_BY", "UPDATED_AT", "UPDATED_BY") values('Global', '35' ,'Legal Collection', current timestamp, 'sql import' , NULL, NULL);
insert into "MDATA"."MDG_PARTY_STATUS" ("LOCALITY","STATUSCODE", "DESCRIPTION", "CREATED_AT", "CREATED_BY", "UPDATED_AT", "UPDATED_BY") values('Global', '40' ,'Out Of Business', current timestamp, 'sql import' , NULL, NULL);

insert into "MDATA"."MDG_PARTY_STATUS" ("LOCALITY","STATUSCODE", "DESCRIPTION", "CREATED_AT", "CREATED_BY", "UPDATED_AT", "UPDATED_BY") values('Local', '10' ,'active', current timestamp, 'sql import' , NULL, NULL);
insert into "MDATA"."MDG_PARTY_STATUS" ("LOCALITY","STATUSCODE", "DESCRIPTION", "CREATED_AT", "CREATED_BY", "UPDATED_AT", "UPDATED_BY") values('Local', '20' ,'Credit Insurance Rejected', current timestamp, 'sql import' , NULL, NULL);
insert into "MDATA"."MDG_PARTY_STATUS" ("LOCALITY","STATUSCODE", "DESCRIPTION", "CREATED_AT", "CREATED_BY", "UPDATED_AT", "UPDATED_BY") values('Local', '30' ,'Bad Payment History', current timestamp, 'sql import' , NULL, NULL);
insert into "MDATA"."MDG_PARTY_STATUS" ("LOCALITY","STATUSCODE", "DESCRIPTION", "CREATED_AT", "CREATED_BY", "UPDATED_AT", "UPDATED_BY") values('Local', '40' ,'Legal Collection/Credit suspended', current timestamp, 'sql import' , NULL, NULL);
insert into "MDATA"."MDG_PARTY_STATUS" ("LOCALITY","STATUSCODE", "DESCRIPTION", "CREATED_AT", "CREATED_BY", "UPDATED_AT", "UPDATED_BY") values('Local', '50' ,'Loss Previous record', current timestamp, 'sql import' , NULL, NULL);
insert into "MDATA"."MDG_PARTY_STATUS" ("LOCALITY","STATUSCODE", "DESCRIPTION", "CREATED_AT", "CREATED_BY", "UPDATED_AT", "UPDATED_BY") values('Local', '60' ,'Payment Suspended/Possible Bankrupcy', current timestamp, 'sql import' , NULL, NULL);
insert into "MDATA"."MDG_PARTY_STATUS" ("LOCALITY","STATUSCODE", "DESCRIPTION", "CREATED_AT", "CREATED_BY", "UPDATED_AT", "UPDATED_BY") values('Local', '80' ,'Inactive', current timestamp, 'sql import' , NULL, NULL);
