CREATE TABLE "MDATA"."DANGEROUS_GOODS_PACKAGE_TYPE" (
		"SHORT_ABBREVIATION" VARCHAR(5) NOT NULL,
		"CREATED_AT" TIMESTAMP,
		"CREATED_BY" VARCHAR(254),
		"UPDATED_AT" TIMESTAMP,
		"UPDATED_BY" VARCHAR(254),
		"REMARKS" VARCHAR(254),
		"TYPE_OF_PACKAGING" VARCHAR(254),
		"OPT_LOCK" BIGINT
	)in TSD0_MDATA_4K index in TSI0_MDATA_4K long in TSL0_MDATA_32K
	DATA CAPTURE NONE
	COMPRESS NO;

ALTER TABLE "MDATA"."DANGEROUS_GOODS_PACKAGE_TYPE" ADD CONSTRAINT "SQL151201101602740" PRIMARY KEY
	("SHORT_ABBREVIATION");
