--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "MDATA"."PACKAGE_TYPE" (
		"SHORT_ABBREVIATION" VARCHAR(5) NOT NULL, 
		"ALLOW_STACK" SMALLINT, 
		"CREATED_AT" TIMESTAMP NOT NULL, 
		"CREATED_BY" VARCHAR(50) NOT NULL, 
		"DESCRIPTION" VARCHAR(50) NOT NULL, 
		"HEIGHT" INTEGER, 
		"LDM" DOUBLE, 
		"LENGHT" INTEGER, 
		"LONG_ABBREVIATION" VARCHAR(50) NOT NULL, 
		"NON_STACK_MAX_HEIGHT" INTEGER, 
		"NON_STACK_MAX_WEIGHT" INTEGER, 
		"STACK_MAX_HEIGHT" INTEGER, 
		"STACK_MAX_WEIGHT" INTEGER, 
		"UPDATED_AT" TIMESTAMP, 
		"UPDATED_BY" VARCHAR(50), 
		"WIDTH" INTEGER
	) in TSD0_MDATA_4K index in TSI0_MDATA_4K long in TSL0_MDATA_32K
	DATA CAPTURE NONE 
	COMPRESS NO;

ALTER TABLE "MDATA"."PACKAGE_TYPE" ADD CONSTRAINT "SQL150424135826550" PRIMARY KEY
	("SHORT_ABBREVIATION");


