ALTER TABLE MDATA.CO_PROFILE
      ALTER COLUMN CREATED_BY 
      SET DATA TYPE varchar(254);

ALTER TABLE MDATA.CO_PROFILE
      ALTER COLUMN UPDATED_BY
      SET DATA TYPE varchar(254);

ALTER TABLE MDATA.CO_PROFILE_KEY
      ALTER COLUMN CREATED_BY
      SET DATA TYPE varchar(254);

ALTER TABLE MDATA.CO_PROFILE_KEY
      ALTER COLUMN UPDATED_BY
      SET DATA TYPE varchar(254);

ALTER TABLE MDATA.CO_PROFILE_MAP
      ALTER COLUMN CREATED_BY
      SET DATA TYPE varchar(254);

ALTER TABLE MDATA.CO_PROFILE_MAP
      ALTER COLUMN UPDATED_BY
      SET DATA TYPE varchar(254);

ALTER TABLE MDATA.CURRENCY
      ALTER COLUMN CREATED_BY
      SET DATA TYPE varchar(254);

ALTER TABLE MDATA.CURRENCY
      ALTER COLUMN UPDATED_BY
      SET DATA TYPE varchar(254);

ALTER TABLE MDATA.INCOTERM
      ALTER COLUMN CREATED_BY
      SET DATA TYPE varchar(254);

ALTER TABLE MDATA.INCOTERM
      ALTER COLUMN UPDATED_BY
      SET DATA TYPE varchar(254);

ALTER TABLE MDATA.MDG_PARTY_STATUS
      ALTER COLUMN CREATED_BY
      SET DATA TYPE varchar(254);

ALTER TABLE MDATA.MDG_PARTY_STATUS
      ALTER COLUMN UPDATED_BY
      SET DATA TYPE varchar(254);

ALTER TABLE MDATA.PACKAGE_TYPE
      ALTER COLUMN CREATED_BY
      SET DATA TYPE varchar(254);

ALTER TABLE MDATA.PACKAGE_TYPE
      ALTER COLUMN UPDATED_BY
      SET DATA TYPE varchar(254);

ALTER TABLE MDATA.REFERENCE_TYPE
      ALTER COLUMN CREATED_BY
      SET DATA TYPE varchar(254);

ALTER TABLE MDATA.REFERENCE_TYPE
      ALTER COLUMN UPDATED_BY
      SET DATA TYPE varchar(254);

ALTER TABLE MDATA.ROLE
      ALTER COLUMN CREATED_BY
      SET DATA TYPE varchar(254);

ALTER TABLE MDATA.ROLE
      ALTER COLUMN UPDATED_BY
      SET DATA TYPE varchar(254);

ALTER TABLE MDATA.TRANSPORT_LOCATION
      ALTER COLUMN CREATED_BY
      SET DATA TYPE varchar(254);

ALTER TABLE MDATA.TRANSPORT_LOCATION
      ALTER COLUMN UPDATED_BY
      SET DATA TYPE varchar(254);

ALTER TABLE MDATA.UN_HAZARD
      ALTER COLUMN CREATED_BY
      SET DATA TYPE varchar(254);

ALTER TABLE MDATA.UN_HAZARD
      ALTER COLUMN UPDATED_BY
      SET DATA TYPE varchar(254);

ALTER TABLE MDATA.UN_HAZARD_BUNDLE
      ALTER COLUMN CREATED_BY
      SET DATA TYPE varchar(254);

ALTER TABLE MDATA.UN_HAZARD_BUNDLE
      ALTER COLUMN UPDATED_BY
      SET DATA TYPE varchar(254);

ALTER TABLE MDATA.UN_HAZARD_TEXT
      ALTER COLUMN CREATED_BY
      SET DATA TYPE varchar(254);

ALTER TABLE MDATA.UN_HAZARD_TEXT
      ALTER COLUMN UPDATED_BY
      SET DATA TYPE varchar(254);
