--<ScriptOptions statementTerminator=";"/>
ALTER TABLE MDATA.DANGEROUS_GOODS
  ADD COLUMN "ADR_IS_DANGEROUS" SMALLINT DEFAULT 0 NOT NULL;

  ALTER TABLE MDATA.DANGEROUS_GOODS
  ADD COLUMN "IATA_IS_DANGEROUS" SMALLINT DEFAULT 0 NOT NULL;

  ALTER TABLE MDATA.DANGEROUS_GOODS
  ADD COLUMN "IMDG_IS_DANGEROUS" SMALLINT DEFAULT 0 NOT NULL;

