--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "MDATA"."CURRENCY" (
		"SHORT_ABBREVIATION" VARCHAR(5) NOT NULL, 
		"CREATED_AT" TIMESTAMP NOT NULL, 
		"CREATED_BY" VARCHAR(50) NOT NULL, 
		"DESCRIPTION" VARCHAR(50), 
		"LONG_ABBREVIATION" VARCHAR(50) NOT NULL, 
		"UPDATED_AT" TIMESTAMP, 
		"UPDATED_BY" VARCHAR(50)
	)in TSD0_MDATA_4K index in TSI0_MDATA_4K long in TSL0_MDATA_32K
	DATA CAPTURE NONE 
	COMPRESS NO;

ALTER TABLE "MDATA"."CURRENCY" ADD CONSTRAINT "SQL150414142247290" PRIMARY KEY
	("SHORT_ABBREVIATION");
