--<ScriptOptions statementTerminator=";"/>
CREATE TABLE "MDATA"."ID_TYPE" (
		"NAME" VARCHAR(254) NOT NULL, 
		"VALUE" BIGINT
	) in TSD0_MDATA_4K index in TSI0_MDATA_4K long in TSL0_MDATA_32K
	DATA CAPTURE NONE 
	COMPRESS NO;

ALTER TABLE "MDATA"."ID_TYPE" ADD CONSTRAINT "SQL150611143853760" PRIMARY KEY
	("NAME");

