//
// Generated By:JAX-WS RI 2.2.4-b01 (JAXB RI IBM 2.2.4-2)
//


package com.dsv.road.masterdata.soap;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;

@WebServiceClient(name = "NumberFountainResourceService", targetNamespace = "http://soap.masterdata.road.dsv.com/", wsdlLocation = "http://localhost:10039/master_data_service-web/NumberFountainResourceService?wsdl")
public class NumberFountainResourceService
    extends Service
{

    private final static URL NUMBERFOUNTAINRESOURCESERVICE_WSDL_LOCATION;
    private final static WebServiceException NUMBERFOUNTAINRESOURCESERVICE_EXCEPTION;
    private final static QName NUMBERFOUNTAINRESOURCESERVICE_QNAME = new QName("http://soap.masterdata.road.dsv.com/", "NumberFountainResourceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9091/master_data_service-web/NumberFountainResourceService/NumberFountainResourceService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NUMBERFOUNTAINRESOURCESERVICE_WSDL_LOCATION = url;
        NUMBERFOUNTAINRESOURCESERVICE_EXCEPTION = e;
    }

    public NumberFountainResourceService() {
        super(__getWsdlLocation(), NUMBERFOUNTAINRESOURCESERVICE_QNAME);
    }

    public NumberFountainResourceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NUMBERFOUNTAINRESOURCESERVICE_QNAME, features);
    }

    public NumberFountainResourceService(URL wsdlLocation) {
        super(wsdlLocation, NUMBERFOUNTAINRESOURCESERVICE_QNAME);
    }

    public NumberFountainResourceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NUMBERFOUNTAINRESOURCESERVICE_QNAME, features);
    }

    public NumberFountainResourceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NumberFountainResourceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NumberFountainResource
     */
    @WebEndpoint(name = "NumberFountainResourcePort")
    public NumberFountainResource getNumberFountainResourcePort() {
        return super.getPort(new QName("http://soap.masterdata.road.dsv.com/", "NumberFountainResourcePort"), NumberFountainResource.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NumberFountainResource
     */
    @WebEndpoint(name = "NumberFountainResourcePort")
    public NumberFountainResource getNumberFountainResourcePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.masterdata.road.dsv.com/", "NumberFountainResourcePort"), NumberFountainResource.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NUMBERFOUNTAINRESOURCESERVICE_EXCEPTION!= null) {
            throw NUMBERFOUNTAINRESOURCESERVICE_EXCEPTION;
        }
        return NUMBERFOUNTAINRESOURCESERVICE_WSDL_LOCATION;
    }

}
